// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8MwI58stqMKCcng6YaErb_5P7zLqdLE',
    appId: '1:1000366602045:web:07194f23b352178f3c3754',
    messagingSenderId: '1000366602045',
    projectId: 'chatapp-8073c',
    authDomain: 'chatapp-8073c.firebaseapp.com',
    storageBucket: 'chatapp-8073c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8lP3Yc2Vz7VGml8MI9RO5vv7yVQxesEo',
    appId: '1:1000366602045:android:d79c08183efc093f3c3754',
    messagingSenderId: '1000366602045',
    projectId: 'chatapp-8073c',
    storageBucket: 'chatapp-8073c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eRYmCIjG78pZPnFGK1GrFI32sUWNhPc',
    appId: '1:1000366602045:ios:4675a7844ccd05ee3c3754',
    messagingSenderId: '1000366602045',
    projectId: 'chatapp-8073c',
    storageBucket: 'chatapp-8073c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
